main: io.github.AndrewL1010.coords.CoordinatePlugin
name: coords
author: Andrew Lu
version: 1.0
api-version: 1.18
commands:
  coords:
    description: Saves/removes coordinates in the coordinate list
    usage:
      /coords save [name]
      /coords set [x] [y] [z]
      /coords list -> lists all coords
      /coords get [name]
      /coords remove [name1] [name2] ... [namex]
    aliases: [ coord, coordinate, coordinates ]
