main: io.github.AndrewL1010.CoordinatePlugin
name: CoordinatePlugin
author: Andrew Lu
version: 1.0
api-version: 1.18
commands:
  coords:
    description: Saves/removes coordinates in the coordinate list
    usage: /<command>
    aliases: [coord][coordinate][coordinates]